name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      Job:
        description: 'Job path'
        required: true
        default: ./src/job.yml
        type: string

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run experiment
      run: az ml job create 
        --subscription 204e6c86-7c06-43db-9194-9603bdef8fad 
        --resource-group tutorial-taam 
        --workspace-name aml-tutorial-taam 
        --file 
        --stream