name: Test Action

on:
  workflow_dispatch:

jobs:
  deploy-dev-job:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: define environment variable
      run: export training_data="azureml://subscriptions/204e6c86-7c06-43db-9194-9603bdef8fad/resourcegroups/tutorial-taam/workspaces/aml-tutorial-taam/datastores/workspaceblobstore/paths/UI/2022-10-18_090538_UTC/"
    - name: Run experiment
      run: echo $training_data